import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
import ThemeProvider from "./context/theme";
import Footer from "./components/Footer";
import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";

const inter = Inter({ subsets: ["latin"] });
const {getUser} = getKindeServerSession();
const user = await getUser();

export const metadata: Metadata = {
  title: "Ecommerce Website",
  description: "Generated by Syed Shahmir Sultan",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
      <ThemeProvider>
        <NavBar user={user}/>{children}<Footer/></ThemeProvider></body>
    </html>
  );
}
