import "./globals.css";
import NavBar from "./components/NavBar";
import ThemeProvider from "./context/theme";
import Footer from "./components/Footer";
import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";
import { Toaster } from "@/components/ui/toaster";
import { KindeUser } from "@kinde-oss/kinde-auth-nextjs/types";
import { Metadata } from "next";

const {getUser} = getKindeServerSession();
const user:KindeUser|null = await getUser();

export const metadata: Metadata = {
  title: "Ecommerce Website",
  description: "Generated by Syed Shahmir Sultan",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <ThemeProvider>
        <Toaster/>
        <NavBar user={user}/>{children}<Footer/></ThemeProvider></body>
    </html>
  );
}
